ivi-input-controller.c: Fix g_ctx declaration causing segfault
g_ctx was declared as a pointer instead of a structure. The problem does not
always occur as it depends on the heap layout. It was observed on qemu-arm
system.

The file is compiled with -Wno-incompatible-pointer-types flag which is hiding
following error:

../../third_party/wayland-ivi-extension/ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c:101:12: error: incompatible pointer types returning 'struct input_context **' from a function with result type 'struct input_context *'; remove & [-Werror,-Wincompatible-pointer-types]
    return &g_ctx;
           ^~~~~~

Signed-off-by: Robert Drab <robert.drab@huawei.com>
Change-Id: I38f7a4f17c611f5d265a3febe81f34e745c6956f